In [58]:
import pandas as pd

In [ ]:
# Reading Data
df = pd.read_csv(r"C:\Users\ELTANANY 01062856027\Downloads\Spaceship Titanic (2).csv")
df.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported,GroupId,GroupSize,TotalSpent,HasSpent,AgeGroup
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False,1,1,0.0,0,adult
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True,2,1,736.0,1,young_adult
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,5390.1,49.0,Altark Susent,False,3,2,9058.1,1,adult
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False,3,2,5176.0,1,young_adult
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True,4,1,1091.0,1,below_teen

In [60]:
# How To Discover Date
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   object
 1   HomePlanet    8492 non-null   object
 2   CryoSleep     8476 non-null   object
 3   Cabin         8494 non-null   object
 4   Destination   8511 non-null   object
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   object
 13  Transported   8693 non-null   bool
 14  GroupId       8693 non-null   int64
 15  GroupSize     8693 non-null   int64
 16  TotalSpent    8693 non-null   float64
 17  HasSpent      8693 non-null   int64
 18  AgeGroup      8693 non-null   object
dtypes: bool(1), float64(7), int64(3), object(8)
memory usage: 1.2+ MB

In [61]:
bool_cols = ['CryoSleep', 'VIP'] # Convert Data Type into boolean [TRUE,FALSE]

for col in bool_cols:
    if col in df.columns:
        df[col] = df[col].astype('boolean')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   object
 1   HomePlanet    8492 non-null   object
 2   CryoSleep     8476 non-null   boolean
 3   Cabin         8494 non-null   object
 4   Destination   8511 non-null   object
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   boolean
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   object
 13  Transported   8693 non-null   bool
 14  GroupId       8693 non-null   int64
 15  GroupSize     8693 non-null   int64
 16  TotalSpent    8693 non-null   float64
 17  HasSpent      8693 non-null   int64
 18  AgeGroup      8693 non-null   object
dtypes: bool(1), boolean(2), float64(7), int64(3), object(6)
memory usage: 1.1+ MB

# Handle Missing Values

In [62]:
#for Spend Money 
spending_cols = ['RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck']
for col in spending_cols:
    df.loc[(df['CryoSleep'] == True) & (df[col].isna()), col] = 0 # 'CryoSleep' == True >> always Sleep mode 

df[spending_cols].isna().sum()

RoomService     113
FoodCourt       113
ShoppingMall    112
Spa             118
VRDeck          126
dtype: int64

In [63]:
# set 0 for other missing values
for col in spending_cols:
    df[col] = df[col].fillna(0)
    
df[spending_cols].isna().sum()

RoomService     0
FoodCourt       0
ShoppingMall    0
Spa             0
VRDeck          0
dtype: int64

In [64]:
#For Age
df['Age'].isna().sum()

179

In [65]:
# Set age accorrding to ['HomePlanet', 'VIP'] otherwise by median 
group_age_median = df.groupby(['HomePlanet', 'VIP'])['Age'].transform('median')
df['Age'] = df['Age'].fillna(group_age_median)

df['Age'] = df['Age'].fillna(df['Age'].median())

df['Age'].isna().sum()

0

In [66]:
# calculate age group 
def make_age_group(age):
    if age <10:
        return 'Kids'
    if age < 13:
        return 'below_teen'
    elif age < 18:
        return 'teen'
    elif age < 35:
        return 'young_adult'
    elif age < 45:
        return 'adult'
    elif age < 60:
        return 'middle_age'
    else:
        return 'senior'

df['AgeGroup'] = df['Age'].apply(make_age_group)
df[['Age', 'AgeGroup']].head()

    Age     AgeGroup
0  39.0        adult
1  24.0  young_adult
2  58.0   middle_age
3  33.0  young_adult
4  16.0         teen

In [67]:
#For Name
df.Name.isna().sum()

200

In [68]:
#Replace na with unkmown
if 'Name' in df.columns:
    df['Name'] = df['Name'].fillna('Unknown')

df.Name.isna().sum()

0

In [69]:
#for Cryosleep 
df.CryoSleep.isna().sum()

217

In [70]:
#Totalspent==0 >>Cryosleep is True
df.loc[df['CryoSleep'].isna() & (df['TotalSpent'] == 0), 'CryoSleep'] = True
df.loc[df['CryoSleep'].isna() & (df['TotalSpent'] > 0), 'CryoSleep'] = False

df['CryoSleep'] = df['CryoSleep'].astype('boolean')
df['CryoSleep'].isna().sum()

0

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   object
 1   HomePlanet    8492 non-null   object
 2   CryoSleep     8693 non-null   boolean
 3   Cabin         8494 non-null   object
 4   Destination   8511 non-null   object
 5   Age           8693 non-null   float64
 6   VIP           8490 non-null   boolean
 7   RoomService   8693 non-null   float64
 8   FoodCourt     8693 non-null   float64
 9   ShoppingMall  8693 non-null   float64
 10  Spa           8693 non-null   float64
 11  VRDeck        8693 non-null   float64
 12  Name          8693 non-null   object
 13  Transported   8693 non-null   bool
 14  GroupId       8693 non-null   int64
 15  GroupSize     8693 non-null   int64
 16  TotalSpent    8693 non-null   float64
 17  HasSpent      8693 non-null   int64
 18  AgeGroup      8693 non-null   object
dtypes: bool(1), boolean(2), float64(7), int64(3), object(6)
memory usage: 1.1+ MB

In [72]:
# for VIP 
df.VIP.isna().sum()

203

In [73]:
# majority is false
if 'VIP' in df.columns:
    df['VIP'] = df['VIP'].fillna(False)

df.VIP.isna().sum()

0

In [74]:
#for destination 
df.Destination.isna().sum()

182

In [75]:
# replace with unknown
for des in df.columns:
    df.Destination=df.Destination.fillna("Unknown")

df.Destination.isna().sum()

0

In [76]:
#drop Na rows in ['Cabin', 'HomePlanet'] option 1 
#df = df.dropna(subset=['Cabin', 'HomePlanet'])

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   object
 1   HomePlanet    8492 non-null   object
 2   CryoSleep     8693 non-null   boolean
 3   Cabin         8494 non-null   object
 4   Destination   8693 non-null   object
 5   Age           8693 non-null   float64
 6   VIP           8693 non-null   boolean
 7   RoomService   8693 non-null   float64
 8   FoodCourt     8693 non-null   float64
 9   ShoppingMall  8693 non-null   float64
 10  Spa           8693 non-null   float64
 11  VRDeck        8693 non-null   float64
 12  Name          8693 non-null   object
 13  Transported   8693 non-null   bool
 14  GroupId       8693 non-null   int64
 15  GroupSize     8693 non-null   int64
 16  TotalSpent    8693 non-null   float64
 17  HasSpent      8693 non-null   int64
 18  AgeGroup      8693 non-null   object
dtypes: bool(1), boolean(2), float64(7), int64(3), object(6)
memory usage: 1.1+ MB

In [79]:
#Option 2 
df['HomePlanet'] = df['HomePlanet'].replace('Unknown', pd.NA)

df['HomePlanet'] = df['HomePlanet'].fillna(df['HomePlanet'].mode()[0])
df.HomePlanet.isna().sum()

0

In [ ]:
#split cabin col
df[['Deck','CabinNum','Side']] = df['Cabin'].str.split('/', expand=True)

In [ ]:
for col in ['Deck', 'Side']:
    # mode >> HomePlanet
    mode_by_home = df.groupby('HomePlanet')[col].agg(
        lambda x: x.mode().iloc[0] if not x.mode().empty else pd.NA
    )
    
    df[col] = df[col].fillna(df['HomePlanet'].map(mode_by_home))
    
    # Otherwise backup mode 
    df[col] = df[col].fillna(df[col].mode()[0])

In [ ]:
df['CabinNum'] = pd.to_numeric(df['CabinNum'], errors='coerce')

# median >> Deck
median_by_deck = df.groupby('Deck')['CabinNum'].transform('median')

df['CabinNum'] = df['CabinNum'].fillna(median_by_deck)

# backup median 
df['CabinNum'] = df['CabinNum'].fillna(df['CabinNum'].median())

#  int
df['CabinNum'] = df['CabinNum'].round().astype('Int64')

In [ ]:
#combination
df['Cabin'] = df['Deck'].astype(str) + '/' + df['CabinNum'].astype(str) + '/' + df['Side'].astype(str)
df.Cabin.isna().sum()

0

In [87]:
path = r"C:\Users\ELTANANY 01062856027\Downloads\Spaceship Titanic (2).csv"

df.to_csv(path, index=False)
print(f'Cleaned file saved as: {path}')

Cleaned file saved as: C:\Users\ELTANANY 01062856027\Downloads\Spaceship Titanic (2).csv